name: nsysu_ap
description: NSYSU AP

version: 0.3.0+300

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common: 0.1.8+1
  #   path: ../../GitHub-NKUST-ITC/ap_common
  ap_common_firbase:
    git:
      url: https://github.com/abc873693/ap_common_firebase
      ref: v0.0.1
  #     path: ../ap_common_firebase

  #official plugin
  shared_preferences: 0.5.6
  package_info: 0.4.0+13
  url_launcher: 5.4.1
  http: 0.12.0+4
  html: ^0.14.0+2
  path_provider: 1.5.1
  webview_flutter: 0.3.21

  #third party plugin
  encrypt: 4.0.0
  cached_network_image: 2.0.0
  sprintf: ^4.0.2
  crypto: ^2.0.6
  big5: 0.0.4
  printing: 3.3.1
  dio: 3.0.9
  dio_cookie_manager: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
