name: nsysu_ap
description: NSYSU AP

version: 0.2.7+207

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common:
    git:
      url: https://github.com/abc873693/ap_common
      ref: v0.1.0
#   path: ../../GitHub-NKUST-ITC/ap_common

  #official plugin
  shared_preferences: 0.5.6
  package_info: 0.4.0+13
  url_launcher: 5.4.1
  firebase_core: 0.4.3+3
  firebase_analytics: 5.0.11
  firebase_remote_config: 0.3.0+1
  firebase_messaging: 6.0.9
  firebase_crashlytics: 0.1.2+5
  http: 0.12.0+4
  html: ^0.14.0+2
  path_provider: 1.5.1
  webview_flutter: 0.3.19+7

  #third party plugin
  encrypt: 4.0.0
  cached_network_image: 2.0.0
  carousel_slider: ^1.2.0
  flutter_local_notifications: 1.1.5+1
  sprintf: ^4.0.2
  crypto: ^2.0.6
  big5: 0.0.4
  printing: 2.1.3
  dio: 3.0.9
  dio_cookie_manager: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
